# Generated by Django 4.2.5 on 2023-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.FloatField()),
            ],
        ),
    ]
